# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweet_app_development
  username: mashijifu
  password: sts0t0i7c
  host: localhost

test:
  <<: *default
  database: tweet_app_test
  username: mashijifu
  password: sts0t0i7c
  host: localhost

production:
  <<: *default
  database: tweet_app_production
  username: tweet_app
  password: <%= ENV['TWEET_APP_DATABASE_PASSWORD'] %>
